# Generated by Django 3.1.6 on 2021-02-11 20:47

from django.db import migrations
  
def create_data(apps, schema_editor):
    Note = apps.get_model('notes', 'Notes')
    Note(task_title="Note 001", description= "Note 001 description").save()

class Migration(migrations.Migration):
 
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_data),
    ]
